// packages/web-components/src/components/pagination/pagination.ts
/**
 * Copyright IBM Corp. 2019, 2025
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import '../button/index';

import { LitElement, html } from 'lit';
import { property, query } from 'lit/decorators.js';

import CDSSelect from '../select/select';
import CaretLeft16 from '@carbon/icons/es/caret--left/16.js';
import CaretRight16 from '@carbon/icons/es/caret--right/16.js';
import FocusMixin from '../../globals/mixins/focus';
import HostListener from '../../globals/decorators/host-listener';
import HostListenerMixin from '../../globals/mixins/host-listener';
import { PAGINATION_SIZE, PAGINATION_TOOLTIP_POSITION } from './defs';
import { carbonElement as customElement } from '../../globals/decorators/carbon-element';
import { iconLoader } from '../../globals/internal/icon-loader';
import { prefix } from '../../globals/settings';
import styles from './pagination.scss.js';

const selectorPagesSelect = `${prefix}-select#pages-select`;
const selectorPageSizesSelect = `${prefix}-select`;
const selectorPreviousButton = `${prefix}--pagination__button--backward`;
const selectorForwardButton = `${prefix}--pagination__button--forward`;

/**
 * Pagination UI.
 *
 * @element cds-pagination
 * @slot page-sizes-select - Where to put in the `<page-sizes-select>`.
 * @fires cds-pagination-changed-current - The custom event fired after the current page is changed from `<cds-pages-select>`.
 * @fires cds-page-sizes-select-changed - The custom event fired after the number of rows per page is changed from `<cds-page-sizes-select>`.
 */
@customElement(`${prefix}-pagination`)
class CDSPagination extends FocusMixin(HostListenerMixin(LitElement)) {
  @query(selectorPageSizesSelect)
  private _pageSizeSelect!: CDSSelect;

  @query(selectorPagesSelect)
  private _pagesSelect!: CDSSelect | null;

  @query(`[button-class-name*=${selectorPreviousButton}]`)
  private _previousButton!: HTMLElement;

  @query(`[button-class-name*=${selectorForwardButton}]`)
  private _forwardButton!: HTMLElement;

  private _handleSlotChange({ target }: Event) {
    const content = (target as HTMLSlotElement).assignedNodes().filter(
      // eslint-disable-next-line @typescript-eslint/no-non-null-assertion -- https://github.com/carbon-design-system/carbon/issues/20452
      (node) => node.nodeType !== Node.TEXT_NODE || node!.textContent!.trim()
    );

    content.forEach((item) => {
      this._pageSizeSelect.appendChild(item);
    });
  }

  /**
   * @returns Page status text.
   */
  private _renderStatusText() {
    const {
      start,
      pageSize,
      totalItems,
      pagesUnknown,
      formatStatusWithDeterminateTotal,
      formatStatusWithIndeterminateTotal,
    } = this;

    const min = totalItems === 0 ? 0 : start + 1;

    if (pagesUnknown || totalItems == null) {
      // * Indeterminate total:
      //   - totalItems === 0 → "0–0 of 0 items"
      //   - else → closed range "1–10 items", "11–20 items", etc.
      if (totalItems === 0) {
        return formatStatusWithDeterminateTotal({ start: 0, end: 0, count: 0 });
      }
      const end = start + pageSize;
      return formatStatusWithIndeterminateTotal({
        start: min,
        end,
        // Use visible range for pluralization, so we get "items" not "item"
        count: Math.max(0, end - start),
      });
    }

    // * Determinate total:
    //   - Regular: "1–10 of 100 items"
    //   - When totalItems === 0 → "0–0 of 0 item"
    return formatStatusWithDeterminateTotal({
      start: min,
      end: Math.min(start + pageSize, totalItems),
      count: totalItems,
    });
  }

  /**
   * Calculates the start value based on `page`, `pageSize`, and `totalItems`
   */
  private _calculateStart(
    page: number,
    pageSize: number,
    totalItems: number | undefined,
    pagesUnknown: boolean
  ): number {
    if (!pagesUnknown && totalItems === 0) return 0;
    const safePageSize = pageSize > 0 ? pageSize : 1;
    const calculatedStart = (Math.max(1, page) - 1) * safePageSize;

    // Only clamp to the last page when the total is determinate
    if (!pagesUnknown && Number.isFinite(totalItems)) {
      const maxStart =
        (Math.ceil((totalItems as number) / safePageSize) - 1) * safePageSize;
      return Math.max(0, Math.min(calculatedStart, maxStart));
    }

    return Math.max(0, calculatedStart);
  }

  /**
   * Handles user-initiated change in the row number the current page starts with.
   *
   * @param start The new current row number, index that starts with zero.
   */
  private _handleUserInitiatedChangeStart(start: number) {
    this.start = start;
    this.dispatchEvent(
      new CustomEvent(
        (this.constructor as typeof CDSPagination).eventChangeCurrent,
        {
          bubbles: true,
          composed: true,
          detail: {
            page: this.page,
            pageSize: this.pageSize,
          },
        }
      )
    );
  }

  /**
   * Handles user-initiated change in the size of the page.
   */
  private _handleUserInitiatedPageSizeChange() {
    this.dispatchEvent(
      new CustomEvent(
        (this.constructor as typeof CDSPagination).eventPageSizeChanged,
        {
          bubbles: true,
          composed: true,
          detail: {
            page: this.page,
            pageSize: this.pageSize,
          },
        }
      )
    );
  }

  /**
   * Handles `click` event on the previous button.
   */
  private _handleClickPrevButton() {
    const { start: oldStart, pageSize } = this;
    this.page--;
    const newStart = Math.max(oldStart - pageSize, 0);
    if (newStart !== oldStart) {
      this._handleUserInitiatedChangeStart(newStart);
    }
    // reset focus to forward button if it reaches the beginning
    if (this.page === 1) {
      this._forwardButton.focus();
    }
  }

  /**
   * Handles `click` event on the next button.
   */
  private _handleClickNextButton() {
    const { start: oldStart, pageSize, totalItems, pagesUnknown } = this;
    this.page++;
    const newStart = oldStart + pageSize;

    if (
      newStart < (totalItems == null ? Infinity : totalItems) ||
      pagesUnknown
    ) {
      this._handleUserInitiatedChangeStart(newStart);
    }
    // reset focus to previous button if it reaches the end and `pagesUnknown` is not true
    if (!pagesUnknown && this.page === this.totalPages) {
      this._previousButton.focus();
    }
  }

  /**
   * Handles user-initiated change in number of rows per page.
   *
   * @param event The event.
   */
  @HostListener(`${prefix}-select-selected`)
  // eslint-disable-next-line @typescript-eslint/ban-ts-comment -- https://github.com/carbon-design-system/carbon/issues/20452
  // @ts-ignore: The decorator refers to this method but TS thinks this method is not referred to
  private _handleChangeSelector(event) {
    const { value } = event.detail;
    const { totalItems, pageSize, pagesUnknown } = this;

    if (event.composedPath()[0] === this._pageSizeSelect) {
      this.pageSize = parseInt(value);
      // Default pageSize to effectively be 1 when we have a value of 0 to avoid
      // division by 0.
      this.totalPages =
        pageSize > 0 ? Math.ceil(totalItems / pageSize) : totalItems;
      this.page = 1;
      this.start = 0;
      this._handleUserInitiatedPageSizeChange();
    } else {
      this.page = Number(value);
      const newStart = this._calculateStart(
        value,
        pageSize,
        totalItems,
        pagesUnknown
      );
      this._handleUserInitiatedChangeStart(newStart);
    }
  }

  /**
   * The assistive text for the button to go to previous page.
   */
  @property({ attribute: 'backward-text' })
  backwardText = 'Previous page';

  /**
   * Specify the position of the tooltip for the backward button. Can be one of: top, right, bottom, or left.
   */
  @property({ attribute: 'backward-text-tooltip-position' })
  backwardTextTooltipPosition = PAGINATION_TOOLTIP_POSITION.TOP;

  /**
   * The current page
   */
  @property({ type: Number, reflect: true })
  page = 1;

  /**
   * The formatter for the assistive text for screen readers to announce.
   * Should be changed upon the locale the UI is rendered with.
   */
  @property({ attribute: false })
  formatLabelText = ({ count }) =>
    `Page of ${count} page${count <= 1 ? '' : 's'}`;

  /**
   * The formatter, used with determinate the total pages. Should be changed upon the locale the UI is rendered with.
   */
  @property({ attribute: false })
  formatStatusWithDeterminateTotal = ({ start, end, count }) =>
    `${start}–${end} of ${count} item${count <= 1 ? '' : 's'}`;

  /**
   * The formatter, used with indeterminate the total pages. Should be changed upon the locale the UI is rendered with.
   */
  @property({ attribute: false })
  formatStatusWithIndeterminateTotal = ({ start, end, count }) =>
    end == null
      ? `Item ${start}–`
      : `${start}–${end} item${count <= 1 ? '' : 's'}`;

  /**
   * The formatter for the text next to the select box. Should be changed upon the locale the UI is rendered with.
   */
  @property({ attribute: false })
  formatSupplementalText = ({ count }) =>
    this.pagesUnknown || !this.totalItems
      ? `page`
      : `of ${count} page${count <= 1 ? '' : 's'}`;
  /**
   * `true` to explicitly state that user is at the last page.
   */
  @property({ type: Boolean, attribute: 'is-last-page' })
  isLastPage!: boolean;

  /**
   * The translatable text indicating the number of items per page.
   */
  @property({ attribute: 'items-per-page-text' })
  itemsPerPageText = '';

  /**
   * `true` if the pagination UI should be disabled.
   */
  @property({ type: Boolean, reflect: true })
  disabled = false;

  /**
   * The assistive text for the button to go to next page.
   */
  @property({ attribute: 'forward-text' })
  forwardText = 'Next page';

  /**
   * Specify the position of the tooltip for the forward button. Can be one of: top, right, bottom, or left.
   */
  @property({ attribute: 'forward-text-tooltip-position' })
  forwardTextTooltipPosition = PAGINATION_TOOLTIP_POSITION.TOP;

  /**
   * true if the select box to change the page should be disabled.
   */
  @property({ type: Boolean, attribute: 'page-input-disabled' })
  pageInputDisabled = false;

  /**
   * Number of items per page.
   */
  @property({ type: Number, attribute: 'page-size', reflect: true })
  pageSize = 10;

  /**
   * true if the select box to change the items per page should be disabled.
   */
  @property({ type: Boolean, attribute: 'page-size-input-disabled' })
  pageSizeInputDisabled;

  /**
   * The label text for the UI to select page size.
   */
  @property({ attribute: 'page-size-label-text' })
  pageSizeLabelText!: string;

  /**
   * true if the total number of items is unknown.
   */
  @property({ type: Boolean, reflect: true, attribute: 'pages-unknown' })
  pagesUnknown = false;

  /**
   * Specify the size of the Pagination.
   */
  @property({ reflect: true })
  size = PAGINATION_SIZE.MEDIUM;

  /**
   * The row number where current page start with, index that starts with zero.
   */
  @property({ type: Number })
  start = 0;

  /**
   * The number of total items.
   */
  @property({
    type: Number,
    attribute: 'total-items',
    converter: {
      fromAttribute: (value) =>
        value === null || value === '' ? undefined : Number(value),
    },
  })
  totalItems!: number;

  /**
   * The number of total pages.
   */
  @property({ type: Number })
  totalPages = 1;

  updated(changedProperties) {
    const { pageSize, totalItems } = this;

    if (changedProperties.has('pageSize')) {
      this._pageSizeSelect.value = String(pageSize ?? '');
    }

    // Recompute total pages and clamp the visible page whenever any relevant input changes
    if (
      changedProperties.has('pageSize') ||
      changedProperties.has('start') ||
      changedProperties.has('totalItems') ||
      changedProperties.has('page')
    ) {
      const computedTotalPages =
        pageSize > 0
          ? Math.ceil((totalItems ?? 0) / pageSize)
          : (totalItems ?? 0);

      // Only assign if it actually changed to avoid unnecessary updates
      if (this.totalPages !== computedTotalPages) {
        this.updateComplete.then(() => {
          this.totalPages = computedTotalPages;
        });
      }

      const totalPagesSafe = Math.max(1, computedTotalPages || 1);
      const requestedPage = Math.max(1, Math.floor(this.page || 1));
      const displayPage = Math.min(requestedPage, totalPagesSafe);

      if (this._pagesSelect) {
        this._pagesSelect.value = displayPage.toString();
      }
    }

    if (changedProperties.has('page')) {
      this.start = this._calculateStart(
        this.page,
        this.pageSize,
        this.totalItems,
        this.pagesUnknown
      );
      if (this._pagesSelect) {
        this._pagesSelect.value = String(this.page);
      }
    }
  }

  render() {
    const {
      page,
      disabled,
      forwardText,
      forwardTextTooltipPosition,
      backwardText,
      backwardTextTooltipPosition,
      itemsPerPageText,
      pageInputDisabled,
      pageSize,
      pageSizeInputDisabled,
      pagesUnknown,
      size,
      start,
      totalItems,
      totalPages,
      _handleClickPrevButton: handleClickPrevButton,
      _handleClickNextButton: handleClickNextButton,
      _handleSlotChange: handleSlotChange,
      formatLabelText,
      formatSupplementalText,
    } = this;

    const { isLastPage = start + pageSize >= totalItems } = this;
    const prevButtonDisabled = disabled || start === 0;
    const nextButtonDisabled = disabled || (!pagesUnknown && isLastPage);

    const prevButtonClassMap = {
      [`${prefix}--btn`]: true,
      [`${prefix}--btn--icon-only`]: true,
      [`${prefix}--pagination__button`]: true,
      [`${prefix}--pagination__button--backward`]: true,
      [`${prefix}--pagination__button--no-index`]: prevButtonDisabled,
      [`${prefix}--btn--${size}`]: true,
      [`${prefix}--btn--ghost`]: true,
    };
    const nextButtonClassMap = {
      [`${prefix}--btn`]: true,
      [`${prefix}--btn--icon-only`]: true,
      [`${prefix}--pagination__button`]: true,
      [`${prefix}--pagination__button--forward`]: true,
      [`${prefix}--pagination__button--no-index`]: nextButtonDisabled,
      [`${prefix}--btn--${size}`]: true,
      [`${prefix}--btn--ghost`]: true,
    };

    const prevButtonClasses = Object.entries(prevButtonClassMap)
      .filter(([, value]) => value === true)
      .map(([key]) => key)
      .join(' ');
    const nextButtonClasses = Object.entries(nextButtonClassMap)
      .filter(([, value]) => value === true)
      .map(([key]) => key)
      .join(' ');

    const totalPagesSafe =
      Number.isFinite(totalPages) && totalPages > 0
        ? totalPages
        : Math.max(1, page || 1);

    return html`
      <div class="${prefix}--pagination__left">
        <cds-select
          ?disabled=${disabled || pageSizeInputDisabled}
          id="page-size-select"
          left-select
          pagination
          size="${size}"
          inline
          value="${pageSize}"
          label-styles-disable>
          <div slot="label-text">
            ${itemsPerPageText &&
            html`<span class="${prefix}--pagination__text"
              >${itemsPerPageText}</span
            >`}
            <slot name="label-text"></slot>
          </div>
          <slot @slotchange=${handleSlotChange}></slot>
        </cds-select>
        <span
          class="${prefix}--pagination__text ${prefix}--pagination__items-count"
          >${this._renderStatusText()}</span
        >
      </div>
      <div class="${prefix}--pagination__right">
        ${pagesUnknown || !totalItems
          ? html`
              <span
                class="${prefix}--pagination__text ${prefix}--pagination__page-text ${prefix}--pagination__unknown-pages-text"
                >${formatSupplementalText({ count: totalPages })} ${page}</span
              >
            `
          : html`
              <cds-select
                ?disabled=${disabled || pageInputDisabled}
                id="pages-select"
                pagination
                size="${size}"
                inline
                value="${page}"
                hide-label>
                <span slot="label-text">
                  ${formatLabelText({ count: totalPages })}
                </span>
                ${Array.from(new Array(totalPagesSafe)).map(
                  (_item, index) => html`
                    <cds-select-item
                      value="${index + 1}"
                      ?selected=${page === index + 1}>
                      ${index + 1}
                    </cds-select-item>
                  `
                )}
              </cds-select>
              <span class="${prefix}--pagination__text"
                >${formatSupplementalText({ count: totalPages })}</span
              >
            `}

        <div class="${prefix}--pagination__control-buttons">
          <cds-button
            tooltip-position=${backwardTextTooltipPosition}
            pagination
            size="${size}"
            ?disabled="${prevButtonDisabled}"
            button-class-name="${prevButtonClasses}"
            tooltip-text="${backwardText}"
            @click="${handleClickPrevButton}">
            ${iconLoader(CaretLeft16, { slot: 'icon' })}
          </cds-button>
          <cds-button
            tooltip-position=${forwardTextTooltipPosition}
            pagination
            size="${size}"
            ?disabled="${nextButtonDisabled}"
            button-class-name="${nextButtonClasses}"
            tooltip-text="${forwardText}"
            @click="${handleClickNextButton}">
            ${iconLoader(CaretRight16, { slot: 'icon' })}
          </cds-button>
        </div>
      </div>
    `;
  }

  /**
   * A selector that will return the select box for the current page.
   */
  static get selectorPagesSelect() {
    return selectorPagesSelect;
  }

  /**
   * A selector that will return the select box for page sizes.
   */
  static get selectorPageSizesSelect() {
    return selectorPageSizesSelect;
  }

  /**
   * A selector that will return the previous button.
   */
  static get selectorPreviousButton() {
    return selectorPreviousButton;
  }

  /**
   * A selector that will return the forward button.
   */
  static get selectorForwardButton() {
    return selectorForwardButton;
  }

  /**
   * The name of the custom event fired after the current row number is changed.
   */
  static get eventChangeCurrent() {
    return `${prefix}-pagination-changed-current`;
  }

  /**
   * The name of the custom event fired after the number of rows per page is changed from `<cds-page-sizes-select>`.
   */
  static get eventPageSizeChanged() {
    return `${prefix}-page-sizes-select-changed`;
  }

  static shadowRootOptions = {
    ...LitElement.shadowRootOptions,
    delegatesFocus: true,
  };
  static styles = styles;
}

export default CDSPagination;

// packages/react/src/components/Pagination/Pagination.tsx
/**
 * Copyright IBM Corp. 2016, 2026
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { CaretLeft, CaretRight } from '@carbon/icons-react';
import React, { useEffect, useMemo, useRef, useState } from 'react';

import { IconButton } from '../IconButton';
import { clamp } from '../../internal/clamp';
import PropTypes from 'prop-types';
import Select from '../Select';
import SelectItem from '../SelectItem';
import cx from 'classnames';
import isEqual from 'react-fast-compare';
import { useFallbackId } from '../../internal/useId';
import { usePreviousValue } from '../../internal/usePreviousValue';
import { usePrefix } from '../../internal/usePrefix';

type ExcludedAttributes = 'id' | 'onChange';

export interface PaginationPageSize {
  text: string;
  value: number;
}

export interface PaginationProps
  extends Omit<React.HTMLAttributes<HTMLDivElement>, ExcludedAttributes> {
  /**
   * The description for the backward icon.
   */
  backwardText?: string;

  /**
   * The tooltip position for the backward button.
   */
  backwardTextTooltipPosition?: 'top' | 'right' | 'bottom' | 'left';

  /**
   * The CSS class names.
   */
  className?: string;

  /**
   * `true` if the backward/forward buttons, as well as the page select elements,  should be disabled.
   */
  disabled?: boolean;

  /**
   * The description for the forward icon.
   */
  forwardText?: string;

  /**
   * The tooltip position for the forward button.
   */
  forwardTextTooltipPosition?: 'top' | 'right' | 'bottom' | 'left';

  /**
   * The unique ID of this component instance.
   */
  id?: string | number;

  // TODO: remove when v9 is deprecated
  /**
   * `true` if the current page should be the last page.
   */
  isLastPage?: boolean;

  /**
   * The function returning a translatable text showing where the current page is,
   * in a manner of the range of items.
   */
  itemRangeText?: (min: number, max: number, total: number) => string;

  /**
   * A variant of `itemRangeText`, used if the total number of items is unknown.
   */
  itemText?: (min: number, max: number) => string;

  /**
   * The translatable text indicating the number of items per page.
   */
  itemsPerPageText?: string;

  /**
   * The callback function called when the current page changes.
   */
  onChange?: (data: {
    page: number;
    pageSize: number;
    // eslint-disable-next-line @typescript-eslint/no-explicit-any -- https://github.com/carbon-design-system/carbon/issues/20452
    ref?: React.RefObject<any>;
  }) => void;

  /**
   * The current page.
   */
  page?: number;

  /**
   * `true` if the select box to change the page should be disabled.
   */
  pageInputDisabled?: boolean;

  pageNumberText?: string;

  /**
   * A function returning PII showing where the current page is.
   */
  pageRangeText?: (current: number, total: number) => string;

  /**
   * A function returning the label for the page select.
   */
  pageSelectLabelText?: (total: number) => string;

  /**
   * Provide a custom render function for the page-selection control.
   * When provided, the default `<Select>` is replaced with the returned node.
   */
  renderPageSelect?: (props: {
    /** The currently active page. */
    currentPage: number;
    /** Total number of pages derived from `totalItems` and `pageSize`. */
    totalPages: number;
    /** Current page size. */
    currentPageSize: number;
    /** The computed accessible label for the page-selection control. */
    pageSelectLabelText: string;
    /** Sets the active page. */
    onSetPage: (page: number | string) => void;
  }) => React.ReactNode;

  /**
   * The number dictating how many items a page contains.
   */
  pageSize?: number;

  /**
   * `true` if the select box to change the items per page should be disabled.
   */
  pageSizeInputDisabled?: boolean;

  /**
   * The choices for `pageSize`.
   */
  pageSizes?: Array<number | PaginationPageSize>;

  /**
   * The translatable text showing the current page.
   */
  pageText?: (page: number, pagesUnknown?: boolean) => string;

  /**
   * `true` when the total number of pages is unknown. Hides the page selection
   * control.
   */
  pagesUnknown?: boolean;

  /**
   * Specify the size of the Pagination.
   */
  size?: 'xs' | 'sm' | 'md' | 'lg';

  /**
   * The total number of items.
   */
  totalItems?: number;
}

const mapPageSizesToObject = (
  sizes: PaginationProps['pageSizes']
): PaginationPageSize[] | undefined =>
  sizes && sizes.length
    ? sizes.map((size) =>
        typeof size === 'object' ? size : { text: String(size), value: size }
      )
    : undefined;

const DEFAULT_PAGE_SIZE = 10;

function renderSelectItems(total) {
  let counter = 1;
  const itemArr: React.ReactNode[] = [];
  while (counter <= total) {
    itemArr.push(
      <SelectItem key={counter} value={counter} text={String(counter)} />
    );
    counter++;
  }
  return itemArr;
}

const getPageSize = (
  pageSizes: PaginationPageSize[] | undefined,
  pageSize?: number
): number => {
  if (!pageSizes) {
    const resolved = pageSize ?? DEFAULT_PAGE_SIZE;
    return resolved > 0 ? resolved : DEFAULT_PAGE_SIZE;
  }
  const hasSize =
    typeof pageSize !== 'undefined' &&
    pageSizes.some((size) => pageSize === size.value);
  return hasSize ? pageSize : pageSizes[0].value;
};

const Pagination = React.forwardRef(
  (
    {
      backwardText = 'Previous page',
      backwardTextTooltipPosition = 'top',
      className: customClassName = '',
      disabled = false,
      forwardText = 'Next page',
      forwardTextTooltipPosition = 'top',
      id,
      isLastPage = false,
      itemText = (min, max) => `${min}–${max} items`,
      itemRangeText = (min, max, total) => `${min}–${max} of ${total} items`,
      itemsPerPageText = 'Items per page:',
      onChange,
      pageNumberText: _pageNumberText,
      pageRangeText = (_current, total) =>
        `of ${total} ${total === 1 ? 'page' : 'pages'}`,
      pageSelectLabelText = (total) =>
        `Page of ${total} ${total === 1 ? 'page' : 'pages'}`,
      page: controlledPage = 1,
      pageInputDisabled,
      renderPageSelect,
      pageSize: controlledPageSize,
      pageSizeInputDisabled,
      pageSizes: controlledPageSizes,
      pageText = (page) => `page ${page}`,
      pagesUnknown = false,
      size = 'md',
      totalItems,
      ...rest
    }: PaginationProps,
    ref: React.Ref<HTMLDivElement>
  ) => {
    const prefix = usePrefix();
    const inputId = useFallbackId(id?.toString());
    const backBtnRef = useRef<HTMLButtonElement>(null);
    const forwardBtnRef = useRef<HTMLButtonElement>(null);
    const pendingChangeRef = useRef<null | { page: number; pageSize: number }>(
      null
    );
    const normalizedControlledPageSizes = useMemo(
      () => mapPageSizesToObject(controlledPageSizes),
      [controlledPageSizes]
    );
    const prevControlledPageSize = usePreviousValue(controlledPageSize);
    const prevControlledPageSizes = usePreviousValue(
      normalizedControlledPageSizes
    );

    const [pageSizes, setPageSizes] = useState(normalizedControlledPageSizes);
    const [page, setPage] = useState(controlledPage);
    const [focusTarget, setFocusTarget] = useState<
      'backward' | 'forward' | null
    >(null);
    const [pageSize, setPageSize] = useState(() => {
      return getPageSize(normalizedControlledPageSizes, controlledPageSize);
    });

    const className = cx({
      [`${prefix}--pagination`]: true,
      [`${prefix}--pagination--${size}`]: size, // TODO: V12 - Remove this class
      [`${prefix}--layout--size-${size}`]: size,
      [customClassName]: !!customClassName,
    });
    const totalPages = totalItems
      ? Math.max(Math.ceil(totalItems / pageSize), 1)
      : 1;
    const backButtonDisabled = disabled || page === 1;
    const backButtonClasses = cx({
      [`${prefix}--pagination__button`]: true,
      [`${prefix}--pagination__button--backward`]: true,
      [`${prefix}--pagination__button--no-index`]: backButtonDisabled,
    });
    const forwardButtonDisabled =
      disabled || (page === totalPages && !pagesUnknown);
    const forwardButtonClasses = cx({
      [`${prefix}--pagination__button`]: true,
      [`${prefix}--pagination__button--forward`]: true,
      [`${prefix}--pagination__button--no-index`]: forwardButtonDisabled,
    });
    const selectItems = renderPageSelect ? [] : renderSelectItems(totalPages);
    const pageSelectNode = pagesUnknown
      ? null
      : (renderPageSelect?.({
          currentPage: page,
          totalPages,
          currentPageSize: pageSize,
          pageSelectLabelText: pageSelectLabelText(totalPages),
          onSetPage: handleSetPage,
        }) ?? null);

    const focusMap = {
      backward: backBtnRef,
      forward: forwardBtnRef,
    };

    const handleFocus = (target: 'backward' | 'forward') => {
      const targetRef = focusMap[target];

      if (targetRef?.current && !targetRef.current.disabled) {
        targetRef.current.focus();
      }
    };

    useEffect(() => {
      if (focusTarget) {
        handleFocus(focusTarget);
        setFocusTarget(null);
      }
      // eslint-disable-next-line  react-hooks/exhaustive-deps -- https://github.com/carbon-design-system/carbon/issues/20452
    }, [focusTarget]);

    useEffect(() => {
      if (pendingChangeRef.current && onChange) {
        onChange(pendingChangeRef.current);

        pendingChangeRef.current = null;
      }
    }, [onChange, page, pageSize]);

    useEffect(() => {
      setPage(controlledPage);
    }, [controlledPage]);

    useEffect(() => {
      if (isEqual(prevControlledPageSizes, normalizedControlledPageSizes)) {
        return;
      }

      if (!normalizedControlledPageSizes) {
        const nextPageSize = getPageSize(undefined, controlledPageSize);

        setPageSizes(undefined);
        setPageSize(nextPageSize);
        return;
      }

      setPageSizes((prev) =>
        isEqual(normalizedControlledPageSizes, prev)
          ? prev
          : normalizedControlledPageSizes
      );

      const nextPageSize = getPageSize(
        normalizedControlledPageSizes,
        controlledPageSize ?? pageSize
      );
      const hasPageSize = normalizedControlledPageSizes.some((size) => {
        return size.value === pageSize;
      });
      const nextPage = hasPageSize ? page : 1;

      const hasControlledPageSize = typeof controlledPageSize !== 'undefined';
      const hasValidControlledPageSize = hasControlledPageSize
        ? normalizedControlledPageSizes.some(
            (size) => size.value === controlledPageSize
          )
        : false;

      // Reset page to 1 if the current pageSize is not included in the new
      // pageSizes.
      if (!hasPageSize) {
        setPage(nextPage);
      }

      if (nextPageSize !== pageSize) {
        setPageSize(nextPageSize);
      }

      if (
        onChange &&
        (!hasControlledPageSize || !hasValidControlledPageSize) &&
        (nextPage !== page || nextPageSize !== pageSize)
      ) {
        pendingChangeRef.current = {
          page: nextPage,
          pageSize: nextPageSize,
        };
      }
    }, [
      controlledPageSize,
      normalizedControlledPageSizes,
      onChange,
      page,
      pageSize,
      prevControlledPageSizes,
    ]);

    useEffect(() => {
      if (controlledPageSize === prevControlledPageSize) return;

      const nextPageSize = getPageSize(
        normalizedControlledPageSizes,
        controlledPageSize
      );

      setPageSize(nextPageSize);
    }, [
      controlledPageSize,
      normalizedControlledPageSizes,
      prevControlledPageSize,
    ]);

    function handleSizeChange(event) {
      const pageSize = Number(event.target.value);
      const changes = {
        pageSize,
        page: 1,
      };

      setPage(changes.page);
      setPageSize(changes.pageSize);

      if (onChange) {
        onChange(changes);
      }
    }

    function handlePageInputChange(event) {
      const page = Number(event.target.value);
      if (
        page > 0 &&
        totalItems &&
        page <= Math.max(Math.ceil(totalItems / pageSize), 1)
      ) {
        setPage(page);

        if (onChange) {
          onChange({
            page,
            pageSize,
          });
        }
      }
    }

    function handleSetPage(nextPage: number | string) {
      if (disabled || pageInputDisabled) return;
      const numericPage = Number(nextPage);
      if (!Number.isInteger(numericPage)) return;
      const clamped = clamp(numericPage, 1, totalPages);
      if (clamped === page) return;
      setPage(clamped);
      if (onChange) {
        onChange({ page: clamped, pageSize });
      }
    }

    function incrementPage() {
      const nextPage = page + 1;
      setPage(nextPage);

      // when the increment button reaches the last page,
      // the icon button becomes disabled and the focus shifts to `main`
      // this presents an a11y problem for keyboard & screen reader users
      // instead, we want the focus to shift to the other pagination btn
      if (nextPage === totalPages) {
        setFocusTarget('backward');
      }

      if (onChange) {
        onChange({
          page: nextPage,
          pageSize,
          ref: backBtnRef,
        });
      }
    }

    function decrementPage() {
      const nextPage = page - 1;
      setPage(nextPage);

      // when the decrement button reaches the first page,
      // the icon button becomes disabled and the focus shifts to `main`
      // this presents an a11y problem for keyboard & screen reader users
      // instead, we want the focus to shift to the other pagination btn
      if (nextPage === 1) {
        setFocusTarget('forward');
      }

      if (onChange) {
        onChange({
          page: nextPage,
          pageSize,
          ref: forwardBtnRef,
        });
      }
    }

    return (
      <div className={className} ref={ref} {...rest}>
        <div
          className={cx(`${prefix}--pagination__left`, {
            [`${prefix}--pagination__left--no-sizer`]: !pageSizes,
          })}>
          {pageSizes && (
            <>
              <label
                id={`${prefix}-pagination-select-${inputId}-count-label`}
                className={`${prefix}--pagination__text`}
                htmlFor={`${prefix}-pagination-select-${inputId}`}>
                {itemsPerPageText}
              </label>
              <Select
                id={`${prefix}-pagination-select-${inputId}`}
                className={`${prefix}--select__item-count`}
                labelText=""
                hideLabel
                noLabel
                inline
                onChange={handleSizeChange}
                disabled={pageSizeInputDisabled || disabled}
                value={pageSize}>
                {pageSizes.map((sizeObj) => (
                  <SelectItem
                    key={sizeObj.value}
                    value={sizeObj.value}
                    text={String(sizeObj.text)}
                  />
                ))}
              </Select>
            </>
          )}
          <span
            className={`${prefix}--pagination__text ${prefix}--pagination__items-count`}>
            {pagesUnknown || !totalItems
              ? totalItems === 0
                ? itemRangeText(0, 0, 0)
                : itemText(pageSize * (page - 1) + 1, page * pageSize)
              : itemRangeText(
                  Math.min(pageSize * (page - 1) + 1, totalItems),
                  Math.min(page * pageSize, totalItems),
                  totalItems
                )}
          </span>
        </div>
        <div
          className={cx(`${prefix}--pagination__right`, {
            [`${prefix}--pagination__right--no-content`]:
              !pagesUnknown && !!renderPageSelect,
          })}>
          {pagesUnknown ? (
            <span
              className={`${prefix}--pagination__text ${prefix}--pagination__page-text ${prefix}--pagination__unknown-pages-text`}>
              {pageText(page)}
            </span>
          ) : (
            <>
              {renderPageSelect ? (
                pageSelectNode
              ) : (
                <Select
                  id={`${prefix}-pagination-select-${inputId}-right`}
                  className={`${prefix}--select__page-number`}
                  labelText={pageSelectLabelText(totalPages)}
                  inline
                  hideLabel
                  onChange={handlePageInputChange}
                  value={page}
                  key={page}
                  disabled={pageInputDisabled || disabled}>
                  {selectItems}
                </Select>
              )}
              <span className={`${prefix}--pagination__text`}>
                {pageSelectNode == null && renderPageSelect
                  ? `${page} ${pageRangeText(page, totalPages)}`
                  : pageRangeText(page, totalPages)}
              </span>
            </>
          )}
          <div className={`${prefix}--pagination__control-buttons`}>
            <IconButton
              align={backwardTextTooltipPosition}
              disabled={backButtonDisabled}
              kind="ghost"
              className={backButtonClasses}
              label={backwardText}
              aria-label={backwardText}
              onClick={decrementPage}
              ref={backBtnRef}>
              <CaretLeft />
            </IconButton>
            <IconButton
              align={forwardTextTooltipPosition}
              disabled={forwardButtonDisabled || isLastPage}
              kind="ghost"
              className={forwardButtonClasses}
              label={forwardText}
              aria-label={forwardText}
              onClick={incrementPage}
              ref={forwardBtnRef}>
              <CaretRight />
            </IconButton>
          </div>
        </div>
      </div>
    );
  }
);

Pagination.propTypes = {
  /**
   * The description for the backward icon.
   */
  backwardText: PropTypes.string,

  /**
   * The tooltip position for the backward button.
   */
  backwardTextTooltipPosition: PropTypes.oneOf([
    'top',
    'right',
    'bottom',
    'left',
  ]),

  /**
   * The CSS class names.
   */
  className: PropTypes.string,

  /**
   * `true` if the backward/forward buttons, as well as the page select elements,  should be disabled.
   */
  disabled: PropTypes.bool,

  /**
   * The description for the forward icon.
   */
  forwardText: PropTypes.string,

  /**
   * The tooltip position for the forward button.
   */
  forwardTextTooltipPosition: PropTypes.oneOf([
    'top',
    'right',
    'bottom',
    'left',
  ]),

  /**
   * The unique ID of this component instance.
   */
  id: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),

  // TODO: remove when v9 is deprecated
  /**
   * `true` if the current page should be the last page.
   */
  isLastPage: PropTypes.bool,

  /**
   * The function returning a translatable text showing where the current page is,
   * in a manner of the range of items.
   */
  itemRangeText: PropTypes.func,

  /**
   * A variant of `itemRangeText`, used if the total number of items is unknown.
   */
  itemText: PropTypes.func,

  /**
   * The translatable text indicating the number of items per page.
   */
  itemsPerPageText: PropTypes.string,

  /**
   * The callback function called when the current page changes.
   */
  onChange: PropTypes.func,

  /**
   * The current page.
   */
  page: PropTypes.number,

  /**
   * `true` if the select box to change the page should be disabled.
   */
  pageInputDisabled: PropTypes.bool,

  pageNumberText: PropTypes.string,

  /**
   * A function returning PII showing where the current page is.
   */
  pageRangeText: PropTypes.func,

  /**
   * A function returning the label for the page select.
   */
  pageSelectLabelText: PropTypes.func,

  /**
   * Provide a custom render function for the page-selection control.
   * When provided, the default `<Select>` is replaced with the returned node.
   */
  renderPageSelect: PropTypes.func,

  /**
   * The number dictating how many items a page contains.
   */
  pageSize: PropTypes.number,

  /**
   * `true` if the select box to change the items per page should be disabled.
   */
  pageSizeInputDisabled: PropTypes.bool,

  /**
   * The choices for `pageSize`.
   */
  pageSizes: PropTypes.arrayOf(
    PropTypes.oneOfType([
      PropTypes.number,
      PropTypes.shape({
        text: PropTypes.string.isRequired,
        value: PropTypes.number.isRequired,
      }),
    ])
  ),

  /**
   * The translatable text showing the current page.
   */
  pageText: PropTypes.func,

  /**
   * `true` if the total number of items is unknown.
   */
  pagesUnknown: PropTypes.bool,

  /**
   * Specify the size of the Pagination.
   */
  size: PropTypes.oneOf(['xs', 'sm', 'md', 'lg']),

  /**
   * The total number of items.
   */
  totalItems: PropTypes.number,
};

export default Pagination;
